- hosts: machines
  tasks:
    - name: Create the installation directory
      file:
        path: "{{ install_dir }}"
        state: directory
        owner: "{{ ansible_user }}"
        recurse: yes
      become: yes

    - name: Create the subdirectories under installation directory
      file:
        path: "{{ install_dir }}/{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        mode: 0755
        recurse: yes
      with_items:
        - "tmp"
        - "mysql"
        - "gitlab/config"
        - "gitlab/data"
        - "log/gitlab"
        - "log/mysql"
        - "log/main_server"
        - "log/load_balancer"

    - name: Creating log directories for execution nodes
      file:
        path: "{{ install_dir }}/log/execution_nodes/execution_node_{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        mode: 0755
        recurse: yes
      with_sequence: start=1 count="{{ number_of_execution_nodes }}"

    - name: Copying files to directories of execution nodes
      copy:
        src: "../../execution_nodes/"
        dest: "{{ install_dir }}/execution_nodes/execution_node_{{ item }}"
        mode: 0755
      with_sequence: start=1 count="{{ number_of_execution_nodes }}"

    - name: Copy files to remaining subdirectories of installation directory
      copy:
        src: "../../{{ item }}/"
        dest: "{{ install_dir }}/{{ item }}/"
        mode: 0755
      with_items:
        - "main_server"
        - "load_balancer"
        - "util"
        - "deploy"
        - "docker-images"
