- hosts: machines
  become: yes
  tasks:
    - raw: which python || apt-get update
    - raw: (which python && which aptitude) || apt-get install -y python python-apt aptitude

    - name: Install pip
      apt: name=python-pip update_cache=true
      when: ansible_distribution == 'Ubuntu'

    - name: Install docker-py
      pip: name=docker-py version=1.9.0
