- hosts: executionnodes
  become: yes
  tasks:

    - name: Register public key
      shell: "cat {{ install_dir }}/deploy/keys/gitlab/execution_nodes/{{ en_dir }}/id_rsa.pub"
      register: ssh_key

    - name: Get Private Token
      uri:
        url: https://{{ gitlab_hostname }}/api/v3/session
        status_code: 201
        method: POST
        body: "login=root&password={{ gitlab_password }}"
        validate_certs: no
        return_content: yes
      register: session_json

    - set_fact:
        session: "{{ session_json.content | from_json }}"

    - name: Add key to gitlab
      uri:
        url: https://{{ gitlab_hostname }}/api/v3/user/keys
        status_code: 201
        method: POST
        body_format: json
        HEADER_PRIVATE-TOKEN: "{{ session.private_token }}"
        body:
          title: "execution-node-{{ ansible_host }}-{{ port }}"
          key: "{{ ssh_key.stdout }}"
        validate_certs: no
        return_content: yes

    - name: Build executionnode
      docker_image:
        name: execution_node
        path: "{{ install_dir }}/execution_nodes/{{ en_dir }}"

    - name: Start execution_node container
      docker_container:
        name: "execution-node-{{ ansible_host }}-{{ port }}"
        image: execution_node
        network_mode: host
        detach: yes
        restart_policy: always
        volumes:
          - "{{ install_dir }}/execution_nodes/{{ en_dir }}:/execution_nodes"
          - "/etc/localtime:/etc/localtime:ro"
          - "{{ install_dir }}/deploy/configs/execution_nodes/{{ en_dir }}:/etc/execution_node"
          - "{{ install_dir }}/deploy/keys/gitlab/execution_nodes/{{ en_dir }}:/root/.ssh/"
          - "{{ install_dir }}/util:/util"
          - "{{ install_dir }}/deploy/configs/util:/etc/util"
          - "{{ install_dir }}/log/execution_nodes/{{ en_dir }}:/log"
        env:
          LOGGERCONFIG: "/etc/util/logger.json"
          GITLAB_IP: "{{ gitlab_hostname }}"
          ENCONFIG: "/etc/execution_node/conf.json"
          ENSCORES: "/etc/execution_node/scores.json"
