- hosts: machines
  become: yes
  tasks:
    - name: Remove autolab directory completely
      file: "dest={{ install_dir }} state=absent"
      ignore_errors: yes

    - name: Remove all images
      docker_image:
        name: "{{ item }}"
        state: absent
      ignore_errors: yes
      with_items:
      - "autolabjs/gitlab-ce:10.1.4-ce.0"
      - "autolabjs/mysql:5.7.4"
      - "autolabjs/nodejs:0.5.0"
      - "autolabjs/executionnode:0.5.0"
      - "main_server"
      - "load_balancer"
      - "execution_node"

    - name: Remove firewall policies
      import_tasks: plays/tasks/ufwreset.yml

    - name: Stop containers
      tag: stop
      docker_container:
        name: "{{ item }}"
        state: stopped
      with_items: 
      - "autolabjs/gitlab-ce:10.1.4-ce.0"
      - "autolabjs/mysql:5.7.4"
      - "autolabjs/nodejs:0.5.0"
      - "autolabjs/executionnode:0.5.0"
      - "main_server"
      - "load_balancer"
      - "execution_node"

    - name: Restart containers
      tag: restart
      docker_container:
        name: "{{ item }}"
        state: started
        restart: yes
      with_items:
      - "autolabjs/gitlab-ce:10.1.4-ce.0"
      - "autolabjs/mysql:5.7.4"
      - "autolabjs/nodejs:0.5.0"
      - "autolabjs/executionnode:0.5.0"
      - "main_server"
      - "load_balancer"
      - "execution_node"

- hosts: all
  become: yes
  tasks:
    - name: Remove crontab from all the machines running AutolabJS components
      cron:
        name: "autolabjs-restart"
        cron_file: "autolabjs"
        state: absent
