- hosts: ms
  become: yes
  tasks:
    - name: Create an out file
      file: path=./logs/ms.txt state=touch

    - name: Clear the file
      shell : truncate -s 0 ./logs/ms.txt

    - name: Build mainserver
      docker_image:
        name: main_server
        path: ./../../main_server
      register: t1

    - name: Adding line for t1 'stdout'
      lineinfile: 
        line: "t1 stdout \n {{t1['stdout']}}"
        path: "./logs/ms.txt"
      when:
        - t1['stdout'] is defined
        - t1['stdout']!=""


    - name: Adding line for t1 'stderr'
      lineinfile: 
        line: "t1 stderr \n {{t1['stderr']}}"
        path: "./logs/ms.txt"
      when: 
        - t1['stderr'] is defined
        - t1['stderr']!=""



    - name: Start mainserver container
      docker_container:
        name: mainserver
        image: main_server
        network_mode: host
        detach: yes
        restart_policy: always
        volumes:
          - "../../main_server:/main_server"
          - "/etc/localtime:/etc/localtime:ro"
          - "../configs/main_server:/etc/main_server"
          - "../../util:/util"
          - "../configs/util:/etc/util"
          - "../../log/main_server:/log"
        env:
          LOGGERCONFIG: "/etc/util/logger.json"
          MSCONFIG: "/etc/main_server/conf.json"
          MSLABCONFIG: "/etc/main_server/labs.json"
          MSCOURSECONFIG: "/etc/main_server/course.json"
          MSAPIKEYS: "/etc/main_server/APIKeys.json"
          #NODE_TLS_REJECT_UNAUTHORIZED: "{{ reject_unauthorised }}"
      register: t2

    - name : Adding line for t2 'stdout'
      lineinfile: 
        line: "t2 stdout\n {{t2['stdout']}}"
        path: "./logs/ms.txt"
      when:
        - t2['stdout'] is defined
        - t2['stdout']!=""

    - name : Adding line for t2 'stderr'
      lineinfile: 
        line: "t2 stderr \n {{t2['stderr']}}"
        path: "./logs/ms.txt"
      when: 
        - t2['stderr'] is defined
        - t2['stderr']!=""

