---
engines:
  shellcheck:
    enabled: true
  checkstyle:
    enabled: true
    channel: "beta"
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
    config:
      config: .eslintrc
  fixme:
    enabled: true
ratings:
  paths:
  - "**.java"
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.sh"
exclude_paths:
- "**.md"
- "**.txt"
- "**.json"
- docs/examples/unit_tests/author_solution/java/lib/
- deploy/wait-for-it.sh
- main_server/public/fonts/
- main_server/public/font/
- main_server/public/css/2fcrYFNaTjcS6g4U3t-Y5ZjZjT5FdEJ140U2DJYC3mY.woff2
- main_server/public/css/icon.css
- tests/functional_tests/data/
- tests/deployment_tests/data/
