- hosts: "{{ item.hostname }}"
  become: yes
  tasks:
    - name: Get Docker installation script
      get_url:
        url: https://get.docker.com
        dest: "/opt/autolabjs/execution_nodes/docker.sh"
        mode: 0775

    - name: Install Docker
      shell: "/opt/autolabjs/execution_nodes/docker.sh"

    - name: Start docker
      service: name=docker state=started

    - name: Register public key
      shell: "cat ./keys/gitlab/execution_nodes/{{ item.nodepath }}/id_rsa.pub"
      register: ssh_key

    - name: Get Private Token
      uri:
        url: https://{{ gitlab_hostname }}/api/v3/session
        status_code: 201
        method: POST
        body: "login=root&password={{ gitlab_password }}"
        validate_certs: no
        return_content: yes
      register: session_json

    - set_fact:
        session: "{{ session_json.content | from_json }}"

    - name: Add key to gitlab
      uri:
        url: https://{{ gitlab_hostname }}/api/v3/user/keys
        status_code: 201
        method: POST
        body_format: json
        HEADER_PRIVATE-TOKEN: "{{ session.private_token }}"
        body:
          title: "execution-node-{{ inventory_hostname }}-{{ item.nodeport }}"
          key: "{{ ssh_key.stdout }}"
        validate_certs: no
        return_content: yes

    - name: Build executionnode
      docker_image:
        name: execution_node
        path: "../execution_nodes/{{ item.nodepath }}"
      when : {{ item.hostname }} == "executionnode1"

    - name: Start execution_node container
      docker_container:
        name: "execution-node-{{ inventory_hostname }}-{{ item.nodeport }}"
        image: execution_node
        network_mode: host
        detach: yes
        restart_policy: always
        volumes:
          - "../execution_nodes/{{ item.nodepath }}:/execution_nodes"
          - "/etc/localtime:/etc/localtime:ro"
          - "./configs/execution_nodes/{{ item.nodepath }}:/etc/execution_node"
          - "./keys/gitlab/execution_nodes/{{ item.nodepath }}:/root/.ssh/"
          - "../util:/util"
          - "./configs/util:/etc/util"
          - "../log/execution_nodes/{{ item.nodepath }}:/log"
        env:
          LOGGERCONFIG: "/etc/util/logger.json"
          GITLAB_IP: "{{ gitlab_hostname }}"
          ENCONFIG: "/etc/execution_node/conf.json"
          ENSCORES: "/etc/execution_node/scores.json"
#          NODE_TLS_REJECT_UNAUTHORIZED: "{{ reject_unauthorised }}"
