- hosts: mysqldb
  become: yes
  tasks:
    - name: Stop and Remove Database Container
      docker_container:
        name: autolab-db
        state: absent
      ignore_errors: yes

    - name: Remove Database Image
      docker_image:
        name: "mysql:latest"
        state: absent
      ignore_errors: yes

- hosts: gitlab
  become: yes
  tasks:
    - name: Stop and Remove Gitlab Container
      docker_container:
        name: gitlab
        state: absent
      ignore_errors: yes

    - name: Remove Gitlab Image
      docker_image:
        name: "gitlab/gitlab-ce:latest"
        state: absent
      ignore_errors: yes

- hosts: lb
  become: yes
  tasks:

    - name: Stop and Remove Loadbalancer container
      docker_container:
        name: loadbalancer
        state: absent
      ignore_errors: yes

    - name: Remove Loadbalancer Image
      docker_image:
        name: load_balancer
        state: absent
      ignore_errors: yes

- hosts: ms
  become: yes
  tasks:

    - name: Stop and remove mainserver container
      docker_container:
        name: mainserver
        state: absent
      ignore_errors: yes

    - name: Remove mainserver Image
      docker_image:
        name: main_server
        state: absent
      ignore_errors: yes

- hosts: executionnodes
  become: yes
  tasks:
    - name: Stop and remove execution_node container
      docker_container:
        name: "execution-node-{{ ansible_host }}-{{ port }}"
        state: absent
      ignore_errors: yes

- hosts: en5
  become: yes
  tasks:
    - name: Remove executionnode Image
      docker_image:
        name: execution_node
        state: absent
      ignore_errors: yes

    - name: Remove autolab directory completely
      file: "dest={{ install_dir }} state=absent"
      ignore_errors: yes
