---
- name: Getting docker script
  get_url:
    url: https://get.docker.com/
    dest: "/tmp/tempdocker.sh"
    mode: 0775

- name: Running docker script
  shell: "/tmp/tempdocker.sh"

- name: Delete tempdocker.sh
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/tmp/tempdocker.sh"

- name: Restarting the docker service
  service:
    name: docker
    state: restarted
